### ISSUE TITLE
Missing from RuneLite Plugin Hub

### ISSUE THREAD

**Issue by FlowOverFail** [pwatts6060/star-info#2]
Hi, someone referred me to this plugin a while ago. Tried to find it in the RuneLite Plugin Hub and I'm not able to see it. Was this plugin removed or just needs to be updated? Thanks. @pwatts6060

**Comment by mishnimpossible** [comment]
Love this plugin! thanks for bringing it back!!!

**Comment by pwatts6060** [comment]
Plugin is indeed back up. There was a hiscores api change required that broke it before.
